//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 10:25:34 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/ticket", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.steinleostolski.settings;
