//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 10:25:34 AM MESZ 
//


package de.steinleostolski.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IT-Bereich" type="{http://www.example.org/ticket}ct_itbereich"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itBereich"
})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(name = "IT-Bereich", required = true)
    protected CtItbereich itBereich;

    /**
     * Gets the value of the itBereich property.
     * 
     * @return
     *     possible object is
     *     {@link CtItbereich }
     *     
     */
    public CtItbereich getITBereich() {
        return itBereich;
    }

    /**
     * Sets the value of the itBereich property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtItbereich }
     *     
     */
    public void setITBereich(CtItbereich value) {
        this.itBereich = value;
    }

}
