//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 07:52:44 PM MESZ 
//


package user;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_supporter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_supporter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://example.org/ticket}userdb"/>
 *         &lt;element name="KnowHow" type="{http://example.org/ticket}stknowhow" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_supporter", propOrder = {
    "userdb",
    "knowHow"
})
public class CtSupporter {

    @XmlElement(required = true)
    protected Userdb userdb;
    @XmlElement(name = "KnowHow", required = true)
    protected List<Stknowhow> knowHow;

    /**
     * Gets the value of the userdb property.
     * 
     * @return
     *     possible object is
     *     {@link Userdb }
     *     
     */
    public Userdb getUserdb() {
        return userdb;
    }

    /**
     * Sets the value of the userdb property.
     * 
     * @param value
     *     allowed object is
     *     {@link Userdb }
     *     
     */
    public void setUserdb(Userdb value) {
        this.userdb = value;
    }

    /**
     * Gets the value of the knowHow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the knowHow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKnowHow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stknowhow }
     * 
     * 
     */
    public List<Stknowhow> getKnowHow() {
        if (knowHow == null) {
            knowHow = new ArrayList<Stknowhow>();
        }
        return this.knowHow;
    }

}
