//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.12 at 07:52:44 PM MESZ 
//


package user;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stknowhow.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="stknowhow">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Hardware"/>
 *     &lt;enumeration value="Software"/>
 *     &lt;enumeration value="OSX"/>
 *     &lt;enumeration value="Windows"/>
 *     &lt;enumeration value="Netzwerk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "stknowhow")
@XmlEnum
public enum Stknowhow {

    @XmlEnumValue("Hardware")
    HARDWARE("Hardware"),
    @XmlEnumValue("Software")
    SOFTWARE("Software"),
    OSX("OSX"),
    @XmlEnumValue("Windows")
    WINDOWS("Windows"),
    @XmlEnumValue("Netzwerk")
    NETZWERK("Netzwerk");
    private final String value;

    Stknowhow(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Stknowhow fromValue(String v) {
        for (Stknowhow c: Stknowhow.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
