//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 12:18:32 PM MESZ 
//


package de.steinleostolski.user;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_profile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_profile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="jabber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vorname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Nachname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Standort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KnowHows" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="KnowHow" type="{http://example.org/ticket}stknowhow" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Tickets" type="{http://example.org/ticket}cttickets"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_profile", propOrder = {
    "id",
    "jabber",
    "vorname",
    "nachname",
    "standort",
    "status",
    "knowHows",
    "tickets"
})
public class CtProfile {

    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;
    @XmlElement(required = true)
    protected String jabber;
    @XmlElement(name = "Vorname", required = true)
    protected String vorname;
    @XmlElement(name = "Nachname", required = true)
    protected String nachname;
    @XmlElement(name = "Standort", required = true)
    protected String standort;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "KnowHows")
    protected CtProfile.KnowHows knowHows;
    @XmlElement(name = "Tickets", required = true)
    protected Cttickets tickets;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the jabber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJabber() {
        return jabber;
    }

    /**
     * Sets the value of the jabber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJabber(String value) {
        this.jabber = value;
    }

    /**
     * Gets the value of the vorname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorname() {
        return vorname;
    }

    /**
     * Sets the value of the vorname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorname(String value) {
        this.vorname = value;
    }

    /**
     * Gets the value of the nachname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNachname() {
        return nachname;
    }

    /**
     * Sets the value of the nachname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNachname(String value) {
        this.nachname = value;
    }

    /**
     * Gets the value of the standort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandort() {
        return standort;
    }

    /**
     * Sets the value of the standort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandort(String value) {
        this.standort = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the knowHows property.
     * 
     * @return
     *     possible object is
     *     {@link CtProfile.KnowHows }
     *     
     */
    public CtProfile.KnowHows getKnowHows() {
        return knowHows;
    }

    /**
     * Sets the value of the knowHows property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtProfile.KnowHows }
     *     
     */
    public void setKnowHows(CtProfile.KnowHows value) {
        this.knowHows = value;
    }

    /**
     * Gets the value of the tickets property.
     * 
     * @return
     *     possible object is
     *     {@link Cttickets }
     *     
     */
    public Cttickets getTickets() {
        return tickets;
    }

    /**
     * Sets the value of the tickets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cttickets }
     *     
     */
    public void setTickets(Cttickets value) {
        this.tickets = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="KnowHow" type="{http://example.org/ticket}stknowhow" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "knowHow"
    })
    public static class KnowHows {

        @XmlElement(name = "KnowHow", required = true)
        protected List<Stknowhow> knowHow;

        /**
         * Gets the value of the knowHow property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the knowHow property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKnowHow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Stknowhow }
         * 
         * 
         */
        public List<Stknowhow> getKnowHow() {
            if (knowHow == null) {
                knowHow = new ArrayList<Stknowhow>();
            }
            return this.knowHow;
        }

    }

}
