//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 01:39:18 PM MESZ 
//


package de.steinleostolski.user;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.steinleostolski.user package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.steinleostolski.user
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cttickets }
     * 
     */
    public Cttickets createCttickets() {
        return new Cttickets();
    }

    /**
     * Create an instance of {@link CtProfile.KnowHows }
     * 
     */
    public CtProfile.KnowHows createCtProfileKnowHows() {
        return new CtProfile.KnowHows();
    }

    /**
     * Create an instance of {@link Userdb }
     * 
     */
    public Userdb createUserdb() {
        return new Userdb();
    }

    /**
     * Create an instance of {@link CtProfile }
     * 
     */
    public CtProfile createCtProfile() {
        return new CtProfile();
    }

}
