//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.24 at 05:10:05 PM MESZ 
//


package de.steinleostolski.ticket;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_ticket complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_ticket">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Infos" type="{http://example.org/ticket}ct_info"/>
 *         &lt;element name="Antworten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Antwort" type="{http://example.org/ticket}ct_antwort" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_ticket", propOrder = {
    "infos",
    "antworten"
})
@XmlSeeAlso({
    Ticket.class
})
public class CtTicket {

    @XmlElement(name = "Infos", required = true)
    protected CtInfo infos;
    @XmlElement(name = "Antworten", required = true)
    protected CtTicket.Antworten antworten;

    /**
     * Gets the value of the infos property.
     * 
     * @return
     *     possible object is
     *     {@link CtInfo }
     *     
     */
    public CtInfo getInfos() {
        return infos;
    }

    /**
     * Sets the value of the infos property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtInfo }
     *     
     */
    public void setInfos(CtInfo value) {
        this.infos = value;
    }

    /**
     * Gets the value of the antworten property.
     * 
     * @return
     *     possible object is
     *     {@link CtTicket.Antworten }
     *     
     */
    public CtTicket.Antworten getAntworten() {
        return antworten;
    }

    /**
     * Sets the value of the antworten property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtTicket.Antworten }
     *     
     */
    public void setAntworten(CtTicket.Antworten value) {
        this.antworten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Antwort" type="{http://example.org/ticket}ct_antwort" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "antwort"
    })
    public static class Antworten {

        @XmlElement(name = "Antwort")
        protected List<CtAntwort> antwort;

        /**
         * Gets the value of the antwort property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the antwort property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAntwort().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CtAntwort }
         * 
         * 
         */
        public List<CtAntwort> getAntwort() {
            if (antwort == null) {
                antwort = new ArrayList<CtAntwort>();
            }
            return this.antwort;
        }

    }

}
