//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 08:42:23 PM MESZ 
//


package de.steinleostolski.ticket;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for st_knowhow.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="st_knowhow">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Hardware"/>
 *     &lt;enumeration value="Software"/>
 *     &lt;enumeration value="OSX"/>
 *     &lt;enumeration value="Windows"/>
 *     &lt;enumeration value="Netzwerk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "st_knowhow")
@XmlEnum
public enum StKnowhow {

    @XmlEnumValue("Hardware")
    HARDWARE("Hardware"),
    @XmlEnumValue("Software")
    SOFTWARE("Software"),
    OSX("OSX"),
    @XmlEnumValue("Windows")
    WINDOWS("Windows"),
    @XmlEnumValue("Netzwerk")
    NETZWERK("Netzwerk");
    private final String value;

    StKnowhow(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StKnowhow fromValue(String v) {
        for (StKnowhow c: StKnowhow.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
