//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.13 at 12:03:03 AM MESZ 
//


package de.steinleostolski.tickets;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.steinleostolski.tickets package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.steinleostolski.tickets
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ticketlist.Teintrag.Tags }
     * 
     */
    public Ticketlist.Teintrag.Tags createTicketlistTeintragTags() {
        return new Ticketlist.Teintrag.Tags();
    }

    /**
     * Create an instance of {@link Ticketlist }
     * 
     */
    public Ticketlist createTicketlist() {
        return new Ticketlist();
    }

    /**
     * Create an instance of {@link Ticketlist.Teintrag }
     * 
     */
    public Ticketlist.Teintrag createTicketlistTeintrag() {
        return new Ticketlist.Teintrag();
    }

}
