//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.14 at 10:13:10 PM MESZ 
//


package de.steinleostolski.tickets;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for st_zustand.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="st_zustand">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="niedrig"/>
 *     &lt;enumeration value="normal"/>
 *     &lt;enumeration value="hoch"/>
 *     &lt;enumeration value="kritisch"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "st_zustand")
@XmlEnum
public enum StZustand {

    @XmlEnumValue("niedrig")
    NIEDRIG("niedrig"),
    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("hoch")
    HOCH("hoch"),
    @XmlEnumValue("kritisch")
    KRITISCH("kritisch");
    private final String value;

    StZustand(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StZustand fromValue(String v) {
        for (StZustand c: StZustand.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
