//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.10 at 01:51:33 PM MESZ 
//


package de.steinleostolski.tickets;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="teintrag" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ticket_id" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   &lt;element name="betreff" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="zustand" type="{http://example.org/ticket}st_zustand"/>
 *                   &lt;element name="bearbeitungszustand" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="tags">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teintrag"
})
@XmlRootElement(name = "ticketlist")
public class Ticketlist {

    protected List<Ticketlist.Teintrag> teintrag;

    /**
     * Gets the value of the teintrag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the teintrag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeintrag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ticketlist.Teintrag }
     * 
     * 
     */
    public List<Ticketlist.Teintrag> getTeintrag() {
        if (teintrag == null) {
            teintrag = new ArrayList<Ticketlist.Teintrag>();
        }
        return this.teintrag;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ticket_id" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         &lt;element name="betreff" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="zustand" type="{http://example.org/ticket}st_zustand"/>
     *         &lt;element name="bearbeitungszustand" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="tags">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ticketId",
        "betreff",
        "datum",
        "zustand",
        "bearbeitungszustand",
        "tags"
    })
    public static class Teintrag {

        @XmlElement(name = "ticket_id", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger ticketId;
        @XmlElement(required = true)
        protected String betreff;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar datum;
        @XmlElement(required = true)
        protected StZustand zustand;
        protected boolean bearbeitungszustand;
        @XmlElement(required = true)
        protected Ticketlist.Teintrag.Tags tags;

        /**
         * Gets the value of the ticketId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTicketId() {
            return ticketId;
        }

        /**
         * Sets the value of the ticketId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTicketId(BigInteger value) {
            this.ticketId = value;
        }

        /**
         * Gets the value of the betreff property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBetreff() {
            return betreff;
        }

        /**
         * Sets the value of the betreff property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBetreff(String value) {
            this.betreff = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the zustand property.
         * 
         * @return
         *     possible object is
         *     {@link StZustand }
         *     
         */
        public StZustand getZustand() {
            return zustand;
        }

        /**
         * Sets the value of the zustand property.
         * 
         * @param value
         *     allowed object is
         *     {@link StZustand }
         *     
         */
        public void setZustand(StZustand value) {
            this.zustand = value;
        }

        /**
         * Gets the value of the bearbeitungszustand property.
         * 
         */
        public boolean isBearbeitungszustand() {
            return bearbeitungszustand;
        }

        /**
         * Sets the value of the bearbeitungszustand property.
         * 
         */
        public void setBearbeitungszustand(boolean value) {
            this.bearbeitungszustand = value;
        }

        /**
         * Gets the value of the tags property.
         * 
         * @return
         *     possible object is
         *     {@link Ticketlist.Teintrag.Tags }
         *     
         */
        public Ticketlist.Teintrag.Tags getTags() {
            return tags;
        }

        /**
         * Sets the value of the tags property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ticketlist.Teintrag.Tags }
         *     
         */
        public void setTags(Ticketlist.Teintrag.Tags value) {
            this.tags = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tag"
        })
        public static class Tags {

            @XmlElement(required = true)
            protected List<String> tag;

            /**
             * Gets the value of the tag property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the tag property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTag().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getTag() {
                if (tag == null) {
                    tag = new ArrayList<String>();
                }
                return this.tag;
            }

        }

    }

}
